spring:
  application:
    name: TodoAPP
  # datasource:
  datasource:
    url: jdbc:postgresql://localhost:5432/tododb
    username: postgres
    password: __password__
    driver-class-name: org.postgresql.Driver
  # jpa:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

  # server:
  port: 8080

# config terminal
logging:
  level:
    root: WARN
